export const studioSampleEvent = {
  title: '新歓飲み会',
  eventDate: '2026-06-15',
  amountPerPerson: 3000,
  paymentMethod: 'cash',
  paymentInfo: '幹事に現金で直接渡してください',
  memo: '',
  adminUrl: '/admin/demo-event?token=admin-demo',
  joinUrl: '/join/demo-event?token=join-demo',
}

export const studioSampleMembers = [
  {
    id: 'sample-member-1',
    name: '角田信夫',
    status: 'reported',
    paymentMethod: 'cash',
    proofMemo: '現金で渡しました',
    updatedAtText: '6/15 23:34',
  },
  {
    id: 'sample-member-2',
    name: '嶋大輔',
    status: 'reported',
    paymentMethod: 'cash',
    proofMemo: '受付で支払い済みです',
    updatedAtText: '6/15 23:34',
  },
  {
    id: 'sample-member-3',
    name: '真島公輝',
    status: 'unpaid',
    paymentMethod: 'cash',
    proofMemo: '',
    updatedAtText: '6/15 23:34',
  },
  {
    id: 'sample-member-4',
    name: '田中太郎',
    status: 'unpaid',
    paymentMethod: 'cash',
    proofMemo: '',
    updatedAtText: '6/15 23:33',
  },
  {
    id: 'sample-member-5',
    name: '佐々木啓介',
    status: 'unpaid',
    paymentMethod: 'cash',
    proofMemo: '',
    updatedAtText: '6/15 23:33',
  },
  {
    id: 'sample-member-6',
    name: '高橋美咲',
    status: 'confirmed',
    paymentMethod: 'cash',
    proofMemo: '受付で確認済み',
    updatedAtText: '6/15 23:32',
  },
  {
    id: 'sample-member-7',
    name: '伊藤蓮',
    status: 'confirmed',
    paymentMethod: 'cash',
    proofMemo: '幹事確認済み',
    updatedAtText: '6/15 23:31',
  },
]
